import Head from 'next/head';
import { gql } from 'apollo-boost';
import { Query, Mutation } from 'react-apollo';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-center">Lets Build Nodebucket2!</div>
    </div>
  )
}